### ISSUE TITLE
Android Studio 3.0 Beta 4 woes

### ISSUE THREAD

**Issue by ljani** [aurae/android-junit5#15]
I've stripped your [sample](https://github.com/aurae/android-junit5/tree/e56aa192ced6d9c1f9d13dc232963240e1034751/sample) and tried to run it with [Android Studio 3.0 Beta 4](https://developer.android.com/studio/archive.html#android-studio-3-0-beta-4) 64-bit on Windows, but it fails with the following error:

```
"C:\Program Files\Java\jdk1.8.0_141\bin\java" ...
Exception in thread "main" java.lang.NoSuchMethodError: org.junit.platform.launcher.Launcher.execute(Lorg/junit/platform/launcher/LauncherDiscoveryRequest;)V
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:61)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

Process finished with exit code 1
```

From previous issues I've gathered that this release should work out-of-the-box with the preview editions of Android Studio. However, I've also tried [the workarounds mentioned in JUnit 5 docs](http://junit.org/junit5/docs/5.0.0-RC3/user-guide/#running-tests-ide-intellij-idea) for IntelliJ IDEA without any luck.

Running from command line works fine:

```
sample ❯❯❯ .\gradlew.bat testDebugUnitTest

> Task :junitPlatformTestDebug
@BeforeAll
@Before Test taggedTest()
@After Test taggedTest()
@Before Test ordinaryTestCase()
@After Test ordinaryTestCase()
@Before Test dynamicTestsGeneratedFromFactory()
@After Test dynamicTestsGeneratedFromFactory()
@Before Test [1] Android's Cool!
@After Test [1] Android's Cool!
@Before Test [2] JUnit 5 as well
@After Test [2] JUnit 5 as well
@Before Test [3] Acknowledgement
@After Test [3] Acknowledgement
@Before Test Test with Custom Display Name in nested class
@After Test Test with Custom Display Name in nested class
@AfterAll

Test run finished after 2465 ms
[         6 containers found      ]
[         0 containers skipped    ]
[         6 containers started    ]
[         0 containers aborted    ]
[         6 containers successful ]
[         0 containers failed     ]
[        10 tests found           ]
[         1 tests skipped         ]
[         9 tests started         ]
[         0 tests aborted         ]
[         9 tests successful      ]
[         0 tests failed          ]



BUILD SUCCESSFUL in 6s
17 actionable tasks: 1 executed, 16 up-to-date
```

I've attached the stripped project if it matters: [android-junit5-sample.zip](https://github.com/aurae/android-junit5/files/1281517/android-junit5-sample.zip)

**Comment by aurae** [comment]
Please refer to the README for the current state of Android Studio & the RC versions of JUnit 5:

```
Note: This plugin also supports the Release Candidates of JUnit 5. However, as of Android Studio 3.0 Beta 3, there is an internal issue with how tests are executed from the IDE related to a removed API in JUnit 5 still accessed from Android Studio's build of IntelliJ. If you run your JUnit 5 tests directly from Android Studio right now, they will fail with a MissingMethodException.
```

The sample project declares a dynamic dependency on the plugin, therefore pulling in the very latest release, which is `1.0.0-RC3`. However, there is a breaking change in the internals of JUnit 5 which broke test execution in the JetBrains IDEs. I'm building this project on IntelliJ's latest version, which has already migrated its Launcher to the new API, but Android Studio hasn't yet caught up to that branch yet. Use `1.0.0-M6` to be compatible with your IDE for now. I'm going to verify each new build of AS to see when they actually pull in the 2017.2.2 IJ branch, but this is an inconvenience we have to take for now.

**Comment by ljani** [comment]
Ah, sorry, I must be blind.

I tried searching for `NoSuchMethodError`, but the readme mentions `MissingMethodException`, which explains why it didn't yield any results.

Thanks.

**Comment by aurae** [comment]
Ah, actually you've got a good point there. I'll update the README to reflect the proper Exception type, and also update the most recent broken build of AS. Thanks!

**Comment by ljani** [comment]
No change with 3.0 Beta 5.

**Comment by aurae** [comment]
Unfortunately no, but you can check the README for a solution to the problem, because I've come up with a workaround. Apply the `android-junit5-embedded-runtime` dependency as a separate entry in your `dependencies` and you can run the tests again.
