### ISSUE TITLE
Support for Android library modules (multi-module setup)?

### ISSUE THREAD

**Issue by alixwar** [aurae/android-junit5#16]
In the README it says:

```
apply plugin: 'com.android.application'
apply plugin: "de.mannodermaus.android-junit5"
```

What about Android library modules? Can you confirm that this works:

```
apply plugin: 'com.android.library'
apply plugin: "de.mannodermaus.android-junit5"
```

?

I'm struggling myself to get a working configuration so sorry for the stupid question. I looked at the sample project but unfortunately it's single module and not showing my setup (multi-module with Android library modules)

I'm getting an error for this line (in the android library submodule):

    dependencies {
       testImplementation junit5()   <-----
    } 

Stacktrace:
```
Could not find method testImplementation() for arguments [[DefaultExternalModuleDependency{group='junit', name='junit', version='4.12', configuration='default'}, DefaultExternalModuleDependency{group='org.junit.jupiter', name='junit-jupiter-api', version='5.0.0', configuration='default'}, DefaultEx
ternalModuleDependency{group='org.junit.platform', name='junit-platform-engine', version='1.0.0', configuration='default'}, DefaultExternalModuleDependency{group='org.junit.platform', name='junit-platform-launcher', version='1.0.0', configuration='default'}, DefaultExternalModuleDependency{group='org
.junit.platform', name='junit-platform-console', version='1.0.0', configuration='default'}, DefaultExternalModuleDependency{group='org.junit.jupiter', name='junit-jupiter-engine', version='5.0.0', configuration='default'}, DefaultExternalModuleDependency{group='org.junit.vintage', name='junit-vintage
-engine', version='4.12.0', configuration='default'}]] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Update:**

testImplementation is new in the upcoming (not released) Android Gradle Plugin...

Changing to testCompile seems to work. I'm able to run the tests but not getting any code coverage due to a missing "junitPlatformTest" task. Is this task called something else using this plugin?

**Comment by alixwar** [comment]
Oh, testImplementation is new in the upcoming (not released) Android Gradle Plugin...

**Comment by aurae** [comment]
Yeah, the plugin [also works in library modules](https://github.com/aurae/android-junit5/blob/master/android-junit5/src/main/groovy/de/mannodermaus/gradle/plugins/android_junit5/AndroidJUnitPlatformPlugin.groovy#L106). I'll make a note to update the README to reflect that more clearly in the future.

Also, just as you mentioned, the README is using the dependency configurations brought in by the 3.x Android Gradle Plugins. If you're on 2.x, the corresponding configuration would be `testCompile` (for `junit5()` and `junit5Params()`) and `testProvided` (for the `embedded-runtime`).
