### ISSUE TITLE
No test results (XML report file)?

### ISSUE THREAD

**Issue by alixwar** [aurae/android-junit5#17]
### Description: 
It looks like the test results (for JUnit 5-style tests) are not written to `$buildDir\test-results\junit-platform\TEST-junit-jupiter.xml`

Ordinary JUnit4 tests are properly reported to: `$buildDir\test-results\junit-platform\TEST-junit-vintage.xml` however.

### Steps to reproduce:
A project with two tests, one regular old school JUnit 4 test:

```
public class FooTest {
   @org.junit.Test
   public void foo() {}
}
```

One JUnit5 test:

```
class FooTests {
    @org.junit.jupiter.api.Test
    void foo() {}
} 
```

Run goal: `gradlew testDebug`

Open folder: `build\test-reults\junit-platform\`
Compare the two XML files (`TEST-junit-vintage.xml` and `TEST-junit-jupiter.xml`). In the vintage XML I find lines such as: 

```
<testcase name="HashCode_WithTwoEqualInstances_ReturnsSameHashCode" classname="com.censored.FooTest" time="0">
<system-out><![CDATA[
unique-id: [engine:junit-vintage]/[runner:com.censored.FooTest]/[test:HashCode_WithTwoEqualInstances_ReturnsSameHashCode(com.censored.FooTest)]
display-name: HashCode_WithTwoEqualInstances_ReturnsSameHashCode
]]></system-out>
</testcase>
```

No such entries in the jupiter file.

Please confirm that this is not just my environment playing a prank on me.

**Comment by aurae** [comment]
Unfortunately, I'm unable to reproduce this with our sample project. When I add a JUnit 4 test class to it and run the tests, each `TestEngine`'s XML file contains `<testcase>` statements for its respective cases (formatting by me):

```xml
TEST-junit-jupiter.xml:

<testcase name="ordinaryTestCase()" classname="ExampleJavaTest" time="0.002">
    <system-out>
        <![CDATA[
        unique-id: [engine:junit-jupiter]/[class:ExampleJavaTest]/[method:ordinaryTestCase()]
        display-name: ordinaryTestCase()
        ]]>
    </system-out>
</testcase>
```

```xml
TEST-junit-vintage.xml:

<testcase name="legacyTest" classname="ExampleLegacyTest" time="0.004">
    <system-out>
        <![CDATA[
        unique-id: [engine:junit-vintage]/[runner:ExampleLegacyTest]/[test:legacyTest(ExampleLegacyTest)]
        display-name: legacyTest
        ]]>
    </system-out>
</testcase>
```

I'm afraid this might actually be your environment after all…

**Comment by alixwar** [comment]
Thank you @aurae 
The sample project is based on unreleased components so maybe that is the "problem". My project is setup according to: https://stackoverflow.com/a/46298696/1859486

**Comment by aurae** [comment]
After changing the sample project to use AGP 2.x, cleaning & re-running, the outcome is the same - the XML reports are generated properly using both jupiter & vintage `TestEngine` implementations. I have set up a [temporary branch](https://github.com/aurae/android-junit5/tree/issue17-sample-agp2x) for demonstration purposes of the 2x-based sample project, including the JUnit 4 test running on vintage.

**Comment by alixwar** [comment]
Great. I will take a look. I noticed that you are using an unreleased version of the Android plugin though:  de.mannodermaus.gradle.plugins:android-junit5:1.0.0.1-SNAPSHOT

It works OK with 1.0.0?

**Comment by alixwar** [comment]
I cannot reproduce this problem on my project. I still have issues with code coverage but it's not related to this. I suspect that my CI environment just didn't run the test because it didn't think it was necessary (no change) which would explain why it was not in the report. Running locally I can see the test result.

**Comment by aurae** [comment]
You're right about the SNAPSHOT version inside the plugin, however the improvements of that are more related to #4 and shouldn't have any further impact on the functionality of the plugin itself. Therefore, `1.0.0` should work just fine! I have also adjusted the `testProvided` dependency declaration to mirror what you would generally use for an "ordinary" project, according to the README.

**Comment by aurae** [comment]
Okay, good to know you've narrowed the issue down!
