### ISSUE TITLE
Facing exception with joptsimple

### ISSUE THREAD

**Issue by prolificcoder** [aurae/android-junit5#2]
Can you update this  https://github.com/aurae/android-junit5/blob/a51a6eb6af48aa8efd2de9fb4e63a7794a5b7c35/gradle.properties#L12
 to JUNIT_PLATFORM_VERSION=1.0.0-M3

I am currently facing https://github.com/junit-team/junit5/issues/576 with this plugin, so I am assuming going to M3 will help? which is showing me
`Caused by: org.junit.platform.joptsimple.UnrecognizedOptionException: all is not a recognized option`

**Comment by aurae** [comment]
Thanks for your report. I assume the the issue is related to the one you linked to, so I will get to updating the dependency shortly.

**Comment by aurae** [comment]
Quick update: This is a little more involved than simply raising the dependency version, since there are quite a few additional extensions that were added in M3. I'll keep you up-to-date on the progress!

**Comment by aurae** [comment]
Thank you for being patient, please excuse the delay. I have just released 1.0.0-M3 to jcenter, you should be able to upgrade now!
